<?php

use yii\db\Schema;
use yii\db\Migration;

class m151125_113602_resize_varchar_fields extends Migration
{
    public function up()
    {
        $this->dropColumn('tradegecko_product', 'search_cache');
        $this->addColumn('tradegecko_product', 'search_cache', "string(5000)");
        $this->dropColumn('tradegecko_product', 'image_url');
        $this->addColumn('tradegecko_product', 'image_url', "string(1000)");
        $this->dropColumn('tradegecko_product', 'product_name');
        $this->addColumn('tradegecko_product', 'product_name', "string(1000)");
        $this->dropColumn('tradegecko_product', 'tags');
        $this->addColumn('tradegecko_product', 'tags', "string(1000)");
        $this->dropColumn('tradegecko_product', 'product_type');
        $this->addColumn('tradegecko_product', 'product_type', "string(1000)");
        $this->dropColumn('tradegecko_product', 'supplier');
        $this->addColumn('tradegecko_product', 'supplier', "string(1000)");
        $this->dropColumn('tradegecko_product', 'vendor');
        $this->addColumn('tradegecko_product', 'vendor', "string(1000)");
        $this->dropColumn('tradegecko_address', 'address1');
        $this->addColumn('tradegecko_address', 'address1', "string(1000)");
        $this->dropColumn('tradegecko_address', 'address2');
        $this->addColumn('tradegecko_address', 'address2', "string(1000)");
        $this->dropColumn('tradegecko_address', 'company_name');
        $this->addColumn('tradegecko_address', 'company_name', "string(1000)");
        $this->dropColumn('tradegecko_address', 'first_name');
        $this->addColumn('tradegecko_address', 'first_name', "string(1000)");
        $this->dropColumn('tradegecko_address', 'last_name');
        $this->addColumn('tradegecko_address', 'last_name', "string(1000)");
        $this->dropColumn('tradegecko_address', 'label');
        $this->addColumn('tradegecko_address', 'label', "string(1000)");
        $this->dropColumn('tradegecko_company', 'website');
        $this->addColumn('tradegecko_company', 'website', "string(1000)");
        $this->dropColumn('tradegecko_company', 'company_name');
        $this->addColumn('tradegecko_company', 'company_name', "string(1000)");
        $this->dropColumn('tradegecko_contact', 'first_name');
        $this->addColumn('tradegecko_contact', 'first_name', "string(1000)");
        $this->dropColumn('tradegecko_contact', 'last_name');
        $this->addColumn('tradegecko_contact', 'last_name', "string(1000)");
        $this->dropColumn('tradegecko_contact', 'location');
        $this->addColumn('tradegecko_contact', 'location', "string(1000)");
        $this->dropColumn('tradegecko_contact', 'notes');
        $this->addColumn('tradegecko_contact', 'notes', "string(5000)");
        $this->dropColumn('tradegecko_fulfillment', 'notes');
        $this->addColumn('tradegecko_fulfillment', 'notes', "string(5000)");
        $this->dropColumn('tradegecko_fulfillment', 'tracking_company');
        $this->addColumn('tradegecko_fulfillment', 'tracking_company', "string(1000)");
        $this->dropColumn('tradegecko_fulfillment', 'tracking_url');
        $this->addColumn('tradegecko_fulfillment', 'tracking_url', "string(1000)");        
        $this->dropColumn('tradegecko_image', 'base_path');
        $this->addColumn('tradegecko_image', 'base_path', "string(1000)");
        $this->dropColumn('tradegecko_image', 'file_name');
        $this->addColumn('tradegecko_image', 'file_name', "string(1000)");
        $this->dropColumn('tradegecko_image', 'image_name');
        $this->addColumn('tradegecko_image', 'image_name', "string(1000)");
        $this->dropColumn('tradegecko_invoice', 'document_url');
        $this->addColumn('tradegecko_invoice', 'document_url', "string(1000)");
        $this->dropColumn('tradegecko_invoice', 'notes');
        $this->addColumn('tradegecko_invoice', 'notes', "string(5000)");
        $this->dropColumn('tradegecko_location', 'address1');
        $this->addColumn('tradegecko_location', 'address1', "string(1000)");
        $this->dropColumn('tradegecko_location', 'address2');
        $this->addColumn('tradegecko_location', 'address2', "string(1000)");
        $this->dropColumn('tradegecko_order', 'notes');
        $this->addColumn('tradegecko_order', 'notes', "string(5000)");
        $this->dropColumn('tradegecko_order', 'source_url');
        $this->addColumn('tradegecko_order', 'source_url', "string(1000)");
        $this->dropColumn('tradegecko_order', 'tax_label');
        $this->addColumn('tradegecko_order', 'tax_label', "string(1000)");
        $this->dropColumn('tradegecko_order', 'tax_override');
        $this->addColumn('tradegecko_order', 'tax_override', "string(1000)");
        $this->dropColumn('tradegecko_order', 'tax_treatment');
        $this->addColumn('tradegecko_order', 'tax_treatment', "string(1000)");
        $this->dropColumn('tradegecko_order', 'tags');
        $this->addColumn('tradegecko_order', 'tags', "string(1000)");
        $this->dropColumn('tradegecko_order', 'url');
        $this->addColumn('tradegecko_order', 'url', "string(1000)");
        $this->dropColumn('tradegecko_order', 'source');
        $this->addColumn('tradegecko_order', 'source', "string(1000)");
        $this->dropColumn('tradegecko_order', 'tracking_number');
        $this->addColumn('tradegecko_order', 'tracking_number', "string(1000)");
        $this->dropColumn('tradegecko_order_line_item', 'image_url');
        $this->addColumn('tradegecko_order_line_item', 'image_url', "string(1000)");
        $this->dropColumn('tradegecko_order_line_item', 'label');
        $this->addColumn('tradegecko_order_line_item', 'label', "string(1000)");
        $this->dropColumn('tradegecko_order_line_item', 'line_type');
        $this->addColumn('tradegecko_order_line_item', 'line_type', "string(1000)");
        $this->dropColumn('tradegecko_payment', 'reference');
        $this->addColumn('tradegecko_payment', 'reference', "string(1000)");
        $this->dropColumn('tradegecko_user', 'avatar_url');
        $this->addColumn('tradegecko_user', 'avatar_url', "string(1000)");
        $this->dropColumn('tradegecko_user', 'first_name');
        $this->addColumn('tradegecko_user', 'first_name', "string(1000)");
        $this->dropColumn('tradegecko_user', 'last_name');
        $this->addColumn('tradegecko_user', 'last_name', "string(1000)");
        $this->dropColumn('tradegecko_user', 'avatar_url');
        $this->addColumn('tradegecko_user', 'avatar_url', "string(1000)");
        $this->dropColumn('tradegecko_user', 'avatar_url');
        $this->addColumn('tradegecko_user', 'avatar_url', "string(1000)");
        $this->dropColumn('tradegecko_variant', 'variant_name');
        $this->addColumn('tradegecko_variant', 'variant_name', "string(1000)");
        $this->dropColumn('tradegecko_variant', 'product_name');
        $this->addColumn('tradegecko_variant', 'product_name', "string(1000)");

    }

    public function down()
    {
        $this->dropColumn('tradegecko_product', 'search_cache');
        $this->dropColumn('tradegecko_product', 'image_url');
        $this->dropColumn('tradegecko_product', 'product_name');
        $this->dropColumn('tradegecko_product', 'tags');
        $this->dropColumn('tradegecko_product', 'product_type');
        $this->dropColumn('tradegecko_product', 'supplier');
        $this->dropColumn('tradegecko_product', 'vendor');
        $this->dropColumn('tradegecko_address', 'address1');
        $this->dropColumn('tradegecko_address', 'address2');
        $this->dropColumn('tradegecko_address', 'company_name');
        $this->dropColumn('tradegecko_address', 'first_name');
        $this->dropColumn('tradegecko_address', 'last_name');
        $this->dropColumn('tradegecko_address', 'label');
        $this->dropColumn('tradegecko_company', 'website');
        $this->dropColumn('tradegecko_company', 'company_name');
        $this->dropColumn('tradegecko_contact', 'last_name');
        $this->dropColumn('tradegecko_contact', 'first_name');
        $this->dropColumn('tradegecko_contact', 'notes');
        $this->dropColumn('tradegecko_contact', 'location');
        $this->dropColumn('tradegecko_fulfillment', 'notes');
        $this->dropColumn('tradegecko_fulfillment', 'tracking_company');
        $this->dropColumn('tradegecko_fulfillment', 'tracking_url');
        $this->dropColumn('tradegecko_image', 'base_path');
        $this->dropColumn('tradegecko_image', 'file_name');
        $this->dropColumn('tradegecko_image', 'image_name');
        $this->dropColumn('tradegecko_invoice', 'document_url');
        $this->dropColumn('tradegecko_invoice', 'notes');
        $this->dropColumn('tradegecko_location', 'address1');
        $this->dropColumn('tradegecko_location', 'address2');
        $this->dropColumn('tradegecko_order', 'notes');
        $this->dropColumn('tradegecko_order', 'source_url');
        $this->dropColumn('tradegecko_order', 'tax_label');
        $this->dropColumn('tradegecko_order', 'tax_override');
        $this->dropColumn('tradegecko_order', 'tax_treatment');
        $this->dropColumn('tradegecko_order', 'tags');
        $this->dropColumn('tradegecko_order', 'url');
        $this->dropColumn('tradegecko_order', 'source');
        $this->dropColumn('tradegecko_order', 'tracking_number');
        $this->dropColumn('tradegecko_order_line_item', 'image_url');
        $this->dropColumn('tradegecko_order_line_item', 'label');
        $this->dropColumn('tradegecko_order_line_item', 'line_type');
        $this->dropColumn('tradegecko_payment', 'reference');
        $this->dropColumn('tradegecko_user', 'first_name');
        $this->dropColumn('tradegecko_user', 'last_name');
        $this->dropColumn('tradegecko_user', 'avatar_url');
        $this->dropColumn('tradegecko_variant', 'variant_name');
        $this->dropColumn('tradegecko_variant', 'product_name');
    }
}
